name: 'CI'

on:
  push:
    branches-ignore:
      - 'release/**'
      - 'docs'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/ci.yml'
      - '.travis.yml'
      - '.gitignore'
      - 'README.md'
      - 'LICENSE'

  pull_request:
    paths:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.1] # Ruby 2.5/2.6은 EOL됨

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for posts's lastmod

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Jekyll Test Script
        run: bash tools/test.sh
